print("Hello! Welcome to the Band Name Generator!")
city = input("What's the name of the city you gre up in?\n")
pet = input("What is the name of a pet?\n")
print("Your band name could be: " + city + " " + pet)
print("ALL! ")